FROM {{ item.image }}

RUN echo $'[Confluent.dist]\n\
name=Confluent repository (dist)\n\
baseurl=https://packages.confluent.io/rpm/5.5/7\n\
gpgcheck=1\n\
gpgkey=https://packages.confluent.io/rpm/5.5/archive.key\n\
enabled=1\n\
\n\
[Confluent]\n\
name=Confluent repository\n\
baseurl=https://packages.confluent.io/rpm/5.5\n\
gpgcheck=1\n\
gpgkey=https://packages.confluent.io/rpm/5.5/archive.key\n\
enabled=1' >> /etc/yum.repos.d/confluent.repo

RUN yum clean all && \
    yum -y install confluent-common-5.5.0-1 \
      confluent-kafka-2.12 \
      confluent-rest-utils-5.5.0-1 \
      confluent-metadata-service-5.5.0-1 \
      confluent-rebalancer-5.5.0-1 \
      confluent-security-5.5.0-1 \